# Generated by Django 3.1.1 on 2020-10-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KlayCalc', '0002_auto_20200925_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of Rate')),
                ('rate', models.FloatField(default=0)),
            ],
        ),
    ]
