# Generated by Django 3.1.1 on 2020-10-12 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KlayCalc', '0003_ratedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donateDate',
        ),
        migrations.AddField(
            model_name='donation',
            name='donate_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of Donate'),
        ),
        migrations.AlterField(
            model_name='ratedata',
            name='date',
            field=models.DateField(default=datetime.datetime.now, editable=False, verbose_name='Date of Rate'),
        ),
    ]
