# Generated by Django 3.1.1 on 2020-10-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KlayCalc', '0004_auto_20201012_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donate_date',
            field=models.DateTimeField(verbose_name='Date of Donate'),
        ),
        migrations.AlterField(
            model_name='ratedata',
            name='date',
            field=models.DateField(verbose_name='Date of Rate'),
        ),
    ]
