# Generated by Django 3.1.1 on 2020-10-12 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KlayCalc', '0005_auto_20201012_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratedata',
            name='date',
            field=models.DateField(default=datetime.datetime.now, editable=False, verbose_name='Date of Rate'),
        ),
    ]
